[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
rayon = "1.10.0"
itertools = "0.14.0"
comfy-table = { version = "7.1", features = ["custom_styling"] }
num-traits = "0.2"
anyhow = "1.0"
compose-macro = "0.1.0"
